Updated "cmpdirs."

diff --git a/bin/cmpdirs b/bin/cmpdirs
--- a/bin/cmpdirs
+++ b/bin/cmpdirs
@@ -1,16 +1,19 @@
 #!/bin/sh
 # This script compares two directories and returns the differences
-# into Differences.txt in the directory of this script.
+# into differences in the directory of this script.
+#
+# Written by Devon Bautista
+# Version: 2.0
 
 # Get current directory script is in
-SCRIPTPATH=$(dirname $0)
-echo $SCRIPTPATH
+ORIG=`pwd`
+cd $(dirname $0)
 
 # Clear terminal window
-clear
+#clear
 
 # Identify user running script
-echo "Running script as $USER."
+echo "Running script as $USER from $(pwd)."
 echo
 
 # Get first directory
@@ -23,9 +26,27 @@ echo "Enter Directory 2: "
 read -r dir2
 echo
 
-# Compare directory differences, sent to Differences.txt
+# Compare directory differences, log errors
 echo "Comparing differences between directories..."
-echo "Differences between directories:" > $SCRIPTPATH/Differences.txt
-echo >> $SCRIPTPATH/Differences.txt
-diff -q -r "$dir1" "$dir2" >> $SCRIPTPATH/Differences.txt
-echo "Done. Check Differences.txt."
+diff -q -r "$dir1" "$dir2" 1>differences 2>errlog
+STATUS=$?
+
+if [ $STATUS -eq 0 ]; then
+	echo "Done. No differences were found between directories."
+	rm errlog
+	rm differences
+elif [ $STATUS -eq 1 ]; then
+	rm errlog
+	echo "Done. Differences between directories found:"
+	cat differences
+	echo "Differences stored in \"$(pwd)/differences\"."
+else
+	rm differences
+	echo "Errors performing \"diff\" occurred:"
+	cat errlog
+	echo "Above errors stored in \"$(pwd)/errlog\"."
+	cd $ORIG
+	exit 1
+fi
+
+cd $ORIG
